- name: gpg keys
  become: true
  become_method: sudo
  apt_key:
    url: "{{ item }}"
    state: present
  with_items:
    - "https://dl.yarnpkg.com/debian/pubkey.gpg"

- name: repos
  become: true
  become_method: sudo
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - "deb https://dl.yarnpkg.com/debian/ stable main"

- name: packages
  become: true
  become_method: sudo
  apt:
    name:
      - nodejs
      - npm
      - yarn
