- name: virt
  include: "{{ distro }}.yml"

- name: create libvirtd group
  become: true
  become_method: sudo
  group:
    name: libvirtd
    state: present

- name: add to group libvirtd
  become: true
  become_method: sudo
  user:
    name: "{{ ansible_user }}"
    groups:
      - libvirtd
    append: "yes"
