- name: packages
  become: true
  become_method: sudo
  apt:
    name:
      - qemu
      - qemu-kvm
      - qemu-system
      - qemu-efi
      - libvirt-daemon-system
      - libvirt-clients
      - bridge-utils
