- name: gpg keys
  become: true
  become_method: sudo
  apt_key:
    url: "{{ item }}"
    state: present
  with_items:
    - "https://download.docker.com/linux/debian/gpg"

- name: repos
  become: true
  become_method: sudo
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - "deb [arch=amd64] https://download.docker.com/linux/{{ distro }} eoan stable"

- name: packages
  become: true
  become_method: sudo
  apt:
    name:
      - docker-ce

- name: docker service
  become: true
  become_method: sudo
  systemd:
    name: docker
    status: started
    enabled: true
