- name: gpg keys
  become: true
  become_method: sudo
  apt_key:
    url: "{{ item }}"
    state: present
  with_items:
    - "https://download.docker.com/linux/debian/gpg"
    - "https://aquasecurity.github.io/trivy-repo/deb/public.key"

- name: repos
  become: true
  become_method: sudo
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ lts_release }} stable"
    - "deb https://aquasecurity.github.io/trivy-repo/deb {{ lts_release }} main"

- name: packages
  become: true
  become_method: sudo
  apt:
    name:
      - docker-ce
      - trivy
      - docker-compose