- name: google sdk packages
  become: true
  become_method: sudo
  aur:
    use: yay
    name:
      - google-cloud-sdk

- name: kubectl
  become: true
  become_method: sudo
  pacman:
    name:
      - kubectl
      - minikube
