- name: apt packages
  become: true
  become_method: sudo
  apt:
    name:
      - bash-completion
      - tmux
      - fzf
      - jq
      - ripgrep
      - rsync
      - htop
      - curl
      - dnsutils
      - direnv
      - nmap
      - yadm
      - s3cmd