- name: python
  include: "{{ distro }}_{{ release }}.yml"

- name: python2 packages
  pip:
    name: ['virtualenv', 'psutil']
    extra_args: --user

- name: python3 packages
  pip:
    name: ['pipenv', 'flake8', 'ansible-lint', 'mycli', 'websocket-client', 'black']
    extra_args: --user
