- name: python
  include: "{{ distro }}_{{ release }}.yml"

- name: python2 packages
  pip:
    name: ['virtualenv', 'psutil']
    executable: '{{ ansible_env.HOME }}/.local/bin/pip2'
    extra_args: --user

- name: python3 packages
  pip:
    name: ['pipenv', 'flake8', 'ansible-lint', 'mycli', 'websocket-client']
    executable: '{{ ansible_env.HOME }}/.local/bin/pip3'
    extra_args: --user
