- name: packages
  become: true
  become_method: sudo
  apt:
    name:
      - python-dev
      - python3-dev
      - python-setuptools
      - python3-setuptools
      - python-pip
      - python3-pip
      - python3-venv
